### ISSUE TITLE
[BUG] Flakey deployments

### ISSUE THREAD

**Issue by charlee-dev** [fossamagna/react-router-amplify#64]
### Describe the problem

Hi, the deployments are still flaky. They pass with certain configurations, but then little change and it is down again, or the deployment finishes successfully in the codebuild, but then opening the URL and I get 500, which exactly happens now. Here are my computer logs:

```

2025-04-21T15:45:16.427Z | Listener started listening port 9898
-- | --
  | 2025-04-21T15:45:16.645Z | node:events:496
  | 2025-04-21T15:45:16.645Z | throw er; // Unhandled 'error' event
  | 2025-04-21T15:45:16.645Z | ^
  | 2025-04-21T15:45:16.645Z | Error: listen EADDRINUSE: address already in use :::9898
  | 2025-04-21T15:45:16.645Z | at Server.setupListenHandle [as _listen2] (node:net:1908:16)
  | 2025-04-21T15:45:16.645Z | at listenInCluster (node:net:1965:12)
  | 2025-04-21T15:45:16.645Z | at Server.listen (node:net:2067:7)
  | 2025-04-21T15:45:16.645Z | at Function.listen (file:///var/task/server.mjs:15644:28)
  | 2025-04-21T15:45:16.645Z | at file:///var/task/server.mjs:45915:5
  | 2025-04-21T15:45:16.645Z | at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
  | 2025-04-21T15:45:16.645Z | at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
  | 2025-04-21T15:45:16.645Z | at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:122:5)
  | 2025-04-21T15:45:16.645Z | Emitted 'error' event on Server instance at:
  | 2025-04-21T15:45:16.645Z | at emitErrorNT (node:net:1944:8)
  | 2025-04-21T15:45:16.645Z | at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  | 2025-04-21T15:45:16.645Z | code: 'EADDRINUSE',
  | 2025-04-21T15:45:16.645Z | errno: -98,
  | 2025-04-21T15:45:16.645Z | syscall: 'listen',
  | 2025-04-21T15:45:16.645Z | address: '::',
  | 2025-04-21T15:45:16.645Z | port: 9898
  | 2025-04-21T15:45:16.645Z | }
  | 2025-04-21T15:45:16.645Z | Node.js v20.18.3
  | 2025-04-21T15:45:16.657Z | INIT_REPORT Init Duration: 369.30 ms Phase: invoke Status: error Error Type: Runtime.ExitError
  | 2025-04-21T15:45:16.657Z | START RequestId: 5d3a2f86-ddf7-4352-b2ab-833eabd8b4cd Version: $LATEST
  | 2025-04-21T15:45:16.667ZREPORT RequestId: 5d3a2f86-ddf7-4352-b2ab-833eabd8b4cd	Duration: 378.88 ms	Billed Duration: 379 ms	Memory Size: 1024 MB	Max Memory Used: 87 MB	Status: error	Error Type: Runtime.ExitError | REPORT RequestId: 5d3a2f86-ddf7-4352-b2ab-833eabd8b4cd Duration: 378.88 ms Billed Duration: 379 ms Memory Size: 1024 MB Max Memory Used: 87 MB Status: error Error Type: Runtime.Exi
```

the app I used for the deployment is your Hello world app with amplify config:
```
version: 1
# applications:
#   - backend:
#       phases:
#         build:
#           commands:
#             - pwd
#             - "ls -al"
#             - echo "node-linker=hoisted" > ../../.npmrc
#             - corepack enable
#             - pnpm install --frozen-lockfile
            # - pnpm exec ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 22
        - nvm use 22
        - node -v
        - npx pnpm install --no-frozen-lockfile
    build:
      commands:
        - npx pnpm --workspace-root build
  artifacts:
    baseDirectory: .amplify-hosting
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
  buildPath: apps/web
appRoot: apps/web
```
